Repository ipdk-io/networking-recipe, pull requests merged in 2023-12, with the labels that each got.

#365 Edits to the IPsec offload documentation
  docs/apps/ipsec-offload.md
Labels: documentation, trivial effort

#368 Add note on OpenSSL version in TLS certs doc
  docs/guides/security/using-tls-certificates.md
Labels: documentation, trivial effort

#369 Add SDE_INSTALL lib path to LD_LIBARY_PATH only if directories exist
  scripts/common/setup_env.sh
Labels: trivial effort

#359 LAG documentation
  docs/apps/lnw/es2k/es2k-linux-networking-lag.md
  docs/apps/lnw/lnw-index.rst
Labels: documentation, medium effort

#377 Update name to use p4cp.recipe and other minor formatting changes
  docs/guides/es2k/building-acc-p4cp.md
  docs/guides/es2k/defining-acc-environment.md
  docs/guides/setup/dpdk-setup-guide.md
  docs/guides/setup/es2k-setup-guide.md
  docs/guides/setup/tofino-setup-guide.md
Labels: documentation, trivial effort

#378 Fix errors in documents
  docs/apps/packet-io.md
  docs/clients/p4rt-ctl.rst
Labels: documentation, trivial effort

#379 Address various issues in LNW documentation
  docs/apps/lnw/es2k/es2k-linux-networking.md
  docs/apps/lnw/es2k/es2k-lnw-overlay-vms.md
  docs/apps/lnw/es2k/linux-networking-for-es2k.md
  docs/apps/lnw/lnw-index.rst
Labels: documentation, trivial effort

#383 Fix documentation
  docs/apps/lnw/es2k/es2k-linux-networking.md
  docs/apps/lnw/es2k/es2k-lnw-overlay-vms.md
  docs/guides/es2k/deploying-p4-programs.md
  docs/guides/es2k/enabling-comm-channel.md
Labels: documentation, medium effort

#322 P4CP configuration file generator
  .gitignore
  docs/scripts/helper-scripts.rst
  docs/scripts/p4cpconfig.rst
  scripts/p4cpconfig.py
Labels: medium effort
