Repository ipdk-io/networking-recipe, pull requests merged in 2023-11, with the labels that each got.

#317 Begin transition to stratum-deps repository
  README.md
  docs/guides/setup/dpdk-setup-guide.md
  docs/guides/setup/es2k-setup-guide.md
  docs/guides/setup/tofino-setup-guide.md
  docs/overview/overview.md
  setup/README.md
Labels: documentation, medium effort

#329 Run clang-format on client source
  clients/gnmi-ctl/gnmi_ctl_utils.c
  clients/gnmi-ctl/gnmi_ctl_utils.h
  clients/p4rt_perf_test/p4rt_perf_simple_l2_demo.cc
  clients/p4rt_perf_test/p4rt_perf_simple_l2_demo.h
  clients/sgnmi_cli/sgnmi_cli.cc
Labels: trivial effort

#330 Run clang-format on ovs-p4rt source
  ovs-p4rt/dpdk/p4_name_mapping.h
  ovs-p4rt/es2k/p4_name_mapping.h
  ovs-p4rt/ovs_p4rt.cc
  ovs-p4rt/ovs_p4rt_session.h
Labels: minor effort

#333 Improve SDE error check
  cmake/FindDpdkDriver.cmake
  cmake/FindEs2kDriver.cmake
  cmake/FindTofinoDriver.cmake
Labels: enhancement, minor effort, cmake

#321 client changes for packetIO
  clients/p4rt-ctl/p4rt-ctl.in
  requirements.txt
Labels: enhancement, medium effort

#327 Use template to generate copy_config_files.sh
  requirements.txt
  scripts/CMakeLists.txt
  scripts/common/copy_config_files.sh.in
  scripts/dpdk/CMakeLists.txt
  scripts/es2k/CMakeLists.txt
  scripts/es2k/copy_config_files.sh
  scripts/gen/copy_config_files.sh.jinja
  scripts/gen/genscript.py
Labels: medium effort, cmake

#289 Update p4rt-ctl to support PacketModMeters
  clients/p4rt-ctl/p4rt-ctl.in
Labels: enhancement, medium effort

#334 Update build documentation for stratum-deps
  docs/guides/deps/building-acc-stratum-deps.md
  docs/guides/deps/building-stratum-deps.md
Labels: documentation, minor effort

#343 Add status badge to README.md
  README.md
Labels: trivial effort, github_actions

#326 Make FindOVS module more robust
  cmake/FindOVS.cmake
Labels: trivial effort, cmake

#344 Create README file for /docs directory
  README.md
  docs/README.md
  setup/README.md
Labels: documentation, trivial effort

#345 Remove invalid packages from requirements.txt
  requirements.txt
Labels: bug

#328 Build p4runtime protobufs
  .github/workflows/pipeline.yml
  .gitignore
  CMakeLists.txt
  cmake/FindHostProtoc.cmake
  cmake/P4RuntimeProtobufs.cmake
  cmake/ProtobufCompile.cmake
  cmake/StratumDependencies.cmake
  protobufs/.gitignore
  protobufs/CMakeLists.txt
  protobufs/README.md
  protobufs/content/LICENSE
  protobufs/content/README.md
  protobufs/content/pyproject.toml
  protobufs/content/setup.cfg.in
  protobufs/content/setup.py
  protobufs/google.cmake
  protobufs/p4runtime.cmake
  protobufs/tarballs.cmake
  protobufs/wheel.cmake
  requirements.txt
Labels: major effort, cmake

#349 Modify FindOVS to update PKG_CONFIG_PATH
  cmake/FindDpdkDriver.cmake
  cmake/FindOVS.cmake
Labels: minor effort, cmake

#347 Improve GitHub workflow
  .github/workflows/pipeline.yml
Labels: github_actions

#361 Add README file to exclude list
  docs/conf.py
Labels: documentation, trivial effort
