Repository ipdk-io/networking-recipe, pull requests merged in 2024-03, with the labels that each got.

#426 Address shellcheck issues
  scripts/common/setup_env.sh
Labels: minor effort

#427 Improve genscript help text
  scripts/gen/genscript.py
Labels: trivial effort

#439 Fix condition for insecure mode check in sgnmi_cli
  clients/sgnmi_cli/sgnmi_cli.cc
Labels: bug, trivial effort

#440 Update p4runtime proto version to 2024.3.0
  protobufs/CMakeLists.txt
Labels: trivial effort, cmake

#441 Add SDE patch scripts to repository
  scripts/common/extract_table_ids_from_p4info.py
  scripts/dpdk/patch-dpdk-sde-rpaths.sh
  scripts/dpdk/set-dpdk-sde-target.sh
  scripts/es2k/patch-es2k-sde-rpaths.sh
  scripts/es2k/set-es2k-sde-target.sh
Labels: minor effort
